name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-961]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build:
    uses: jstz-dev/jstz/.github/workflows/docker.yml@huanchengchang/jstz-961
    with:
      ref: huanchengchang/jstz-961
      octez_version: 23.2
      dry_run: true
    secrets: inherit
