name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-941-1-test]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build-image:
    name: Build image
    uses: jstz-dev/jstz/.github/workflows/docker.yml@huanchengchang/jstz-941-1-test
    with:
      octez-tag: 23.2
      dry_run: true
      ref: 5d9e62aa2f847082c2513993275a7d7d2d9e503f
    secrets: inherit
